In [1]:
import pandas as pd

# 5 yılın dosyasını ayrı ayrı okuyup bir sözlükte tutuyoruz
yillar = [2015, 2016, 2017, 2018, 2019]
ham_veriler = {yil: pd.read_csv(f"{yil}.csv") for yil in yillar}

for yil, df in ham_veriler.items():
    print(f"{yil}: {df.shape[0]} satır, {df.shape[1]} sütun")

2015: 158 satır, 12 sütun
2016: 157 satır, 13 sütun
2017: 155 satır, 12 sütun
2018: 156 satır, 9 sütun
2019: 156 satır, 9 sütun

In [2]:
# SORUNU GÖRELİM: her yılın sütun isimleri birbirinden farklı!
for yil, df in ham_veriler.items():
    print(f"--- {yil} ---")
    print(list(df.columns), "\n")

--- 2015 ---
['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Standard Error', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']

--- 2016 ---
['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Lower Confidence Interval', 'Upper Confidence Interval', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']

--- 2017 ---
['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high', 'Whisker.low', 'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.', 'Freedom', 'Generosity', 'Trust..Government.Corruption.', 'Dystopia.Residual']

--- 2018 ---
['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

--- 2019 ---
['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

In [3]:
# Ortak şema: her yıldaki farklı ismi tek bir standart isme eşliyoruz
esleme = {
    2015: {"Country": "Ulke", "Happiness Rank": "Sira", "Happiness Score": "Skor",
           "Economy (GDP per Capita)": "GSYH", "Family": "Sosyal_Destek",
           "Health (Life Expectancy)": "Saglik", "Freedom": "Ozgurluk",
           "Trust (Government Corruption)": "Yolsuzluk_Algisi", "Generosity": "Comertlik"},
    2016: {"Country": "Ulke", "Happiness Rank": "Sira", "Happiness Score": "Skor",
           "Economy (GDP per Capita)": "GSYH", "Family": "Sosyal_Destek",
           "Health (Life Expectancy)": "Saglik", "Freedom": "Ozgurluk",
           "Trust (Government Corruption)": "Yolsuzluk_Algisi", "Generosity": "Comertlik"},
    2017: {"Country": "Ulke", "Happiness.Rank": "Sira", "Happiness.Score": "Skor",
           "Economy..GDP.per.Capita.": "GSYH", "Family": "Sosyal_Destek",
           "Health..Life.Expectancy.": "Saglik", "Freedom": "Ozgurluk",
           "Trust..Government.Corruption.": "Yolsuzluk_Algisi", "Generosity": "Comertlik"},
    2018: {"Country or region": "Ulke", "Overall rank": "Sira", "Score": "Skor",
           "GDP per capita": "GSYH", "Social support": "Sosyal_Destek",
           "Healthy life expectancy": "Saglik", "Freedom to make life choices": "Ozgurluk",
           "Perceptions of corruption": "Yolsuzluk_Algisi", "Generosity": "Comertlik"},
    2019: {"Country or region": "Ulke", "Overall rank": "Sira", "Score": "Skor",
           "GDP per capita": "GSYH", "Social support": "Sosyal_Destek",
           "Healthy life expectancy": "Saglik", "Freedom to make life choices": "Ozgurluk",
           "Perceptions of corruption": "Yolsuzluk_Algisi", "Generosity": "Comertlik"},
}

# Tüm yıllarda ortak olan sütunlar (bazı sütunlar her yılda olmadığı için sadece bunları tutacağız)
ortak_sutunlar = ["Ulke", "Sira", "Skor", "GSYH", "Sosyal_Destek",
                  "Saglik", "Ozgurluk", "Comertlik", "Yolsuzluk_Algisi"]

temiz_parcalar = []
for yil in yillar:
    df = ham_veriler[yil].rename(columns=esleme[yil])   # sütun isimlerini standartlaştır
    df["Yil"] = yil                                      # hangi yıla ait olduğunu ekle
    temiz_parcalar.append(df[["Yil"] + ortak_sutunlar])  # sadece ortak sütunları al

# concat ile 5 yılı tek DataFrame'de birleştiriyoruz
veri = pd.concat(temiz_parcalar, ignore_index=True)
print("Birleşik veri boyutu:", veri.shape)
veri.head()

Birleşik veri boyutu: (782, 10)

,Yil,Ulke,Sira,Skor,GSYH,Sosyal_Destek,Saglik,Ozgurluk,Comertlik,Yolsuzluk_Algisi
0,2015,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978
1,2015,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145
2,2015,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357
3,2015,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503
4,2015,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957

In [4]:
veri.info()   # veri tipleri ve dolu değer sayıları

<class 'pandas.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Yil               782 non-null    int64
 1   Ulke              782 non-null    str
 2   Sira              782 non-null    int64
 3   Skor              782 non-null    float64
 4   GSYH              782 non-null    float64
 5   Sosyal_Destek     782 non-null    float64
 6   Saglik            782 non-null    float64
 7   Ozgurluk          782 non-null    float64
 8   Comertlik         782 non-null    float64
 9   Yolsuzluk_Algisi  781 non-null    float64
dtypes: float64(7), int64(2), str(1)
memory usage: 61.2 KB

In [5]:
# Eksik değer var mı? Sütun bazında sayalım
veri.isnull().sum()

Yil                 0
Ulke                0
Sira                0
Skor                0
GSYH                0
Sosyal_Destek       0
Saglik              0
Ozgurluk            0
Comertlik           0
Yolsuzluk_Algisi    1
dtype: int64

In [6]:
# Eksik değerin olduğu satırı görelim
veri[veri["Yolsuzluk_Algisi"].isnull()]

,Yil,Ulke,Sira,Skor,GSYH,Sosyal_Destek,Saglik,Ozgurluk,Comertlik,Yolsuzluk_Algisi
489,2018,United Arab Emirates,20,6.774,2.096,0.776,0.67,0.284,0.186,NaN

In [7]:
# 2018'de Birleşik Arap Emirlikleri'nin yolsuzluk algısı değeri boş.
# Silmek yerine, o YILIN medyanı ile dolduruyoruz (derste öğrendiğimiz strateji)
yil_2018_medyan = veri.loc[veri["Yil"] == 2018, "Yolsuzluk_Algisi"].median()
print("2018 yılı medyanı:", yil_2018_medyan)

veri["Yolsuzluk_Algisi"] = veri["Yolsuzluk_Algisi"].fillna(yil_2018_medyan)
print("Doldurma sonrası eksik değer sayısı:", veri["Yolsuzluk_Algisi"].isnull().sum())

2018 yılı medyanı: 0.082
Doldurma sonrası eksik değer sayısı: 0

In [8]:
print("Tamamen aynı olan satır sayısı        :", veri.duplicated().sum())
print("Aynı (Ülke, Yıl) ikilisine sahip satır:", veri.duplicated(subset=["Ulke", "Yil"]).sum())
# İkisi de 0 -> yinelenen kayıt yok. Olsaydı veri.drop_duplicates() ile temizlerdik.

Tamamen aynı olan satır sayısı        : 0
Aynı (Ülke, Yıl) ikilisine sahip satır: 0

In [9]:
# Sira sütunu sıralama bilgisi olduğu için tam sayı (int) olmalı
veri["Sira"] = veri["Sira"].astype(int)
veri["Yil"] = veri["Yil"].astype(int)

veri.dtypes

Yil                   int64
Ulke                    str
Sira                  int64
Skor                float64
GSYH                float64
Sosyal_Destek       float64
Saglik              float64
Ozgurluk            float64
Comertlik           float64
Yolsuzluk_Algisi    float64
dtype: object

In [10]:
# Her ülkenin kaç kez geçtiğini sayalım; 5'ten az olanları listeleyelim
ulke_sayimi = veri["Ulke"].value_counts()
supheli = ulke_sayimi[ulke_sayimi < 5]
print("5'ten az görünen ülke sayısı:", len(supheli))
supheli

5'ten az görünen ülke sayısı: 29

Ulke
Taiwan                      4
Hong Kong                   4
Macedonia                   4
Mozambique                  4
Lesotho                     4
Laos                        4
Sudan                       4
Angola                      4
Central African Republic    4
Somalia                     4
Namibia                     4
South Sudan                 4
Trinidad and Tobago         3
North Cyprus                3
Comoros                     3
Belize                      3
Suriname                    2
Swaziland                   2
Trinidad & Tobago           2
Northern Cyprus             2
Oman                        1
Somaliland region           1
Djibouti                    1
Puerto Rico                 1
Somaliland Region           1
Taiwan Province of China    1
Hong Kong S.A.R., China     1
North Macedonia             1
Gambia                      1
Name: count, dtype: int64

In [11]:
# Listeye bakınca aynı ülkenin farklı yazımlarını görüyoruz:
# "Trinidad and Tobago" (3) + "Trinidad & Tobago" (2) = aslında 5!
# Bunları tek isimde birleştiriyoruz (replace ile)
isim_duzeltme = {
    "Trinidad & Tobago":        "Trinidad and Tobago",
    "Northern Cyprus":          "North Cyprus",
    "Taiwan Province of China": "Taiwan",
    "Hong Kong S.A.R., China":  "Hong Kong",
    "North Macedonia":          "Macedonia",
    "Somaliland Region":        "Somaliland region",
}
veri["Ulke"] = veri["Ulke"].replace(isim_duzeltme)

# Kontrol: düzeltme sonrası bu ülkeler artık 5'er kez görünüyor mu?
kontrol_listesi = ["Trinidad and Tobago", "North Cyprus", "Taiwan", "Hong Kong", "Macedonia"]
veri[veri["Ulke"].isin(kontrol_listesi)]["Ulke"].value_counts()

Ulke
Taiwan                 5
Trinidad and Tobago    5
North Cyprus           5
Hong Kong              5
Macedonia              5
Name: count, dtype: int64

In [12]:
# Yıl ve sıraya göre sıralayıp indeksi sıfırlıyoruz
veri = veri.sort_values(["Yil", "Sira"]).reset_index(drop=True)
veri.head()

,Yil,Ulke,Sira,Skor,GSYH,Sosyal_Destek,Saglik,Ozgurluk,Comertlik,Yolsuzluk_Algisi
0,2015,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978
1,2015,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145
2,2015,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357
3,2015,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503
4,2015,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957

In [13]:
veri.to_csv("mutluluk_2015_2019_temiz.csv", index=False)   # index=False: indeks sütununu dosyaya yazma
print("Temiz veri kaydedildi:", veri.shape[0], "satır,", veri.shape[1], "sütun")

Temiz veri kaydedildi: 782 satır, 10 sütun

In [14]:
def mutluluk_verisi_temizle(dosya_yollari: dict, esleme: dict, isim_duzeltme: dict) -> pd.DataFrame:
    """5 yıllık mutluluk raporu dosyalarını okuyup tek temiz DataFrame döndürür.

    Adımlar: sütun standartlaştırma -> birleştirme -> eksik doldurma ->
             duplicate kontrolü -> tip düzeltme -> isim tutarlılığı -> indeks düzenleme
    """
    ortak = ["Ulke", "Sira", "Skor", "GSYH", "Sosyal_Destek",
             "Saglik", "Ozgurluk", "Comertlik", "Yolsuzluk_Algisi"]

    parcalar = []
    for yil, yol in dosya_yollari.items():
        df = pd.read_csv(yol).rename(columns=esleme[yil])
        df["Yil"] = yil
        parcalar.append(df[["Yil"] + ortak])

    v = pd.concat(parcalar, ignore_index=True)

    # eksik değerleri kendi yılının medyanıyla doldur (groupby + transform)
    v["Yolsuzluk_Algisi"] = v.groupby("Yil")["Yolsuzluk_Algisi"].transform(lambda s: s.fillna(s.median()))

    v = v.drop_duplicates(subset=["Ulke", "Yil"])          # olası duplicate'leri at
    v["Sira"] = v["Sira"].astype(int)                       # tip düzeltme
    v["Ulke"] = v["Ulke"].replace(isim_duzeltme)            # isim tutarlılığı
    return v.sort_values(["Yil", "Sira"]).reset_index(drop=True)


# Fonksiyonu test edelim
dosyalar = {yil: f"{yil}.csv" for yil in yillar}
temiz = mutluluk_verisi_temizle(dosyalar, esleme, isim_duzeltme)
print("Fonksiyonla temizlenen veri:", temiz.shape)
print("Eksik değer:", temiz.isnull().sum().sum())
temiz.head()

Fonksiyonla temizlenen veri: (782, 10)
Eksik değer: 0

,Yil,Ulke,Sira,Skor,GSYH,Sosyal_Destek,Saglik,Ozgurluk,Comertlik,Yolsuzluk_Algisi
0,2015,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978
1,2015,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145
2,2015,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357
3,2015,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503
4,2015,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957

In [15]:
# Yıllara göre dünya mutluluk ortalaması
print("Yıllara göre dünya ortalaması:")
print(veri.groupby("Yil")["Skor"].mean().round(3))
print()

# 5 yılın genel ortalamasına göre en mutlu 5 ülke
print("2015-2019 ortalamasına göre en mutlu 5 ülke:")
print(veri.groupby("Ulke")["Skor"].mean().sort_values(ascending=False).head().round(3))

Yıllara göre dünya ortalaması:
Yil
2015    5.376
2016    5.382
2017    5.354
2018    5.376
2019    5.407
Name: Skor, dtype: float64

2015-2019 ortalamasına göre en mutlu 5 ülke:
Ulke
Denmark        7.546
Norway         7.541
Finland        7.538
Switzerland    7.511
Iceland        7.511
Name: Skor, dtype: float64